### ISSUE TITLE
Error: connect ECONNREFUSED 127.0.0.1:4304

### ISSUE THREAD

**Issue by Dar-S** [mspetik/pimatic-owjs#1]
I enabled the OWJS plugin, but it does not work, producing quite annoying error:
[pimatic-owjs] error read value of OWFS sensor ASR.temp.01: Error: connect ECONNREFUSED 127.0.0.1:4304

I am sure that the OWFS system is working on my computer, as I can read the 1-wire devices in all ways:
 - via http (owhttpd)
 - via ftp (owftpd )
 - as a mounted file system (owfs)

I see that all OWFS services are up and running:
 - /usr/bin/owserver -c /etc/owfs.conf --pid-file /var/run/owfs/owserver.pid
 - /usr/bin/owhttpd -c /etc/owfs.conf --pid-file /var/run/owfs/owhttpd.pid
 - /usr/bin/owftpd -c /etc/owfs.conf --pid-file /var/run/owfs/owftpd.pid
 - /usr/lib/owfs/owfs -c /etc/owfs.conf

So in principle the OWFS on my computer is quite well configured and it just works.
Why then the 'pimatic-owjs' complains about connection error?
How should I troubleshoot further this issue?

Regards,
-DarS

**Comment by Dar-S** [comment]
Gosh, childish issue I see...
My problem with ECONNREFUSED 127.0.0.1:4304 was resolved by a simple reconfiguration of OWFS setup. It was enough to replace the 'localhost' with '127.0.0.1' lines.
So simple...

Could you please add this step to the list of prerequisites for 'pimatic-owjs' plugin?
Otherwise other people will get stuck with the same error, because the **default** OWFS config is with 'localhost' and not with 127.0.0.1. 
And because for humans these two (localhost and 127.0.0.1) mean exactly the same, it is difficult to spot such a subtle difference.

My current OWFS config file (it gives no ECONNREFUSED 127.0.0.1:4304 error anymore):
`/etc/owfs.conf
######################## SOURCES ########################
#! server: server = localhost:4304
! server: server = 127.0.0.1:4304

####################### OWSERVER ########################
#server: port = localhost:4304
server: port = 127.0.0.1:4304
`

**Comment by mspetik** [comment]
Thank you
Yes, it is necessary to adjust owfs.conf
README file edit.
Settings can be:
server: port = 127.0.0.1:4304 access only from localhost
server: port = 0.0.0.0:4304 - access from all addresses
