### ISSUE TITLE
Any chance for DS2423 counter support?

### ISSUE THREAD

**Issue by Dar-S** [mspetik/pimatic-owjs#2]
Kind request for considering DS2423 support. This 1-Wire chip (1D class) is a 16-bit dual-counter device. 
A bit rare nowadays I must say, but I use two of them for energy consumption measurement. They just count pulses available on any modern professional energy counter/meter.
You then read the output, e.g.:
 - counter.A	104
 - counter.B	5206307
I would appreciate considering support for DS2423 in 'owjs' plugin. I can contribute with testing & troubleshooting if needed.
Regards,
-Dar-S

**Comment by mspetik** [comment]
A few days ago some arrived. I added support for DS2423. I'd want to add count per time.

**Comment by Dar-S** [comment]
Thanks!  
Of course I could not resist to test it :-)
The update to "pimatic-owjs@0.1.6" went smoothly. I rebooted my Pimatic, but unfortunately I could not add the new owjsSensor device. I filled up everything (using web GUI) but got "Oops... Cannot read property 'toUpperCase' of undefined" error instead.
How could I troubleshoot further this issue?
Regards,
-Dar-S

**Comment by mspetik** [comment]
Try to fill the attributeName field, for example counter.

**Comment by Dar-S** [comment]
Wow. Thanks!
It just ... works :-)
I'm glad to see the power consumption from one of my DS2423 counters. I really appreciate your work and engagement!
